### ISSUE TITLE
Unable to get capabilities for monitor

### ISSUE THREAD

**Issue by yochananmarqos** [digitaltrails/vdu_controls#15]
I just added an MSI G27C4 monitor to the mix, it seems VDU Controls doesn't like it?

The error dialog shows the last line in the output below as well as:

```
Is --sleep-multiplier set too low?
```

I removed `~/.config/vdu_controls/*` to no avail.

`vdu-controls` 1.5.7-1 (AUR package)
`ddcutil` 1.2.2-1
`i2c-tools` 4.3-3

```
❯ vdu_controls
INFO: checking for config file '/home/yochanan/.config/vdu_controls/vdu_controls.conf'
INFO: using config file '/home/yochanan/.config/vdu_controls/vdu_controls.conf'
INFO: application style is adwaita-dark
INFO: checking Display 1
   I2C bus:  /dev/i2c-2
   Monitor:             MSI:MSI G27C4:
INFO: checking Display 2
   I2C bus:  /dev/i2c-3
   Monitor:             HPN:HP X24ih:1CR1261L9W
WARNING: ignoring Invalid display
   I2C bus:  /dev/i2c-4
   Monitor:             NCP::
INFO: checking Display 3
   I2C bus:  /dev/i2c-5
   Monitor:             HPN:HP X24ih:1CR1060B95
INFO: checking for config file '/home/yochanan/.config/vdu_controls/MSI_G27C4_Display1.conf'
INFO: checking for config file '/home/yochanan/.config/vdu_controls/MSI_G27C4.conf'
Unable to get capabilities for monitor on Display_Handle[i2c: fd=3, busno=2 @0x55bb8667e590].  Maximum DDC retries exceeded.
ERROR:
 Traceback (most recent call last):
  File "/usr/bin/vdu_controls", line 2414, in <module>
    main()
  File "/usr/bin/vdu_controls", line 2252, in main
    main_window = MainWindow(main_config, app)
  File "/usr/bin/vdu_controls", line 2160, in __init__
    self.main_control_panel = VduControlsMainPanel(main_config, detect_vdu_hook, app_context_menu)
  File "/usr/bin/vdu_controls", line 1616, in __init__
    controller = VduController(vdu_id, vdu_model_name, vdu_serial, manufacturer, default_config, self.ddcutil)
  File "/usr/bin/vdu_controls", line 973, in __init__
    self.capabilities_text = ddcutil.query_capabilities(vdu_id)
  File "/usr/bin/vdu_controls", line 525, in query_capabilities
    result = self.__run__('--display', vdu_id, 'capabilities')
  File "/usr/bin/vdu_controls", line 495, in __run__
    result = subprocess.run(
  File "/usr/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ddcutil', '--sleep-multiplier', '0.5', '--display', '1', 'capabilities']' returned non-zero exit status 1.
```

**Comment by digitaltrails** [comment]
We need to find out what is going wrong with the ddcutil command underlying vdu_controls.

What is the output of the same ddcutil command if it is run in a X11 terminal (such as xterm, konsole, ...)?  The command to enter would be:

`ddcutil --sleep-multiplier 0.5 --display 1 capabilities`

If that errors, does increasing the sleep multiplier to 1.0 or even 2.0 make any difference?

How is MSI G27C4 connected, DVI, Displayport, or USB?

**Comment by yochananmarqos** [comment]
```
❯ ddcutil --sleep-multiplier 0.5 --display 1 capabilities
Unable to get capabilities for monitor on Display_Handle[i2c: fd=3, busno=2 @0x55bcf406e590].  Maximum DDC retries exceeded.
```

The other two identical HP displays have normal output.

**Comment by digitaltrails** [comment]
Thanks for the info.

Oh, USB-C, that's probably the issue.  I don't think anyone with a USB connected monitor has tried vdu_controls until now.  There is a section on USB on the ddcutil website: [https://www.ddcutil.com/usb/](https://www.ddcutil.com/usb/)

If you were interested in experimenting, if you could read the ddcutil website and figure out what parameters need to be passed to talk to your monitor, I could then endeavour to figure out a way to work them into vdu_controls.  I guess I need a way to figure out that a monitor is USB connected so that I can use the ddcutil USB related commands to talk to it.  It may be necessary to add a command line parameter to at least point vdu_controls in the right direction.  I'm not actually sure because I don't have a USB-C connectable monitor to play with.

In the meantime I think you could get vdu_controls running for non-USB monitors (presuming you have some) by creating a dummy config file for the USB connected monitor that disables it in vdu_controls.  You could create a file called `/home/yochanan/.config/vdu_controls/MSI_G27C4.conf` with the following content:

```
[vdu-controls-widgets]
brightness = no
contrast = no
audio-volume = no
audio-mute = no
audio-treble = no
audio-bass = no
audio-mic-volume = no
input-source = no
power-mode = no
osd-language = no
enable-vcp-codes = 

[ddcutil-parameters]
sleep-multiplier = 0.5

[ddcutil-capabilities]
capabilities-override =

```

**Comment by digitaltrails** [comment]
I should probably popup a "should this monitor be ignored" question if I get this kind of error.  Then there would at least be a way to continue on with the GUI for the other monitors.

**Comment by yochananmarqos** [comment]
Not quite:

```
❯ ddcutil --display 1 getvcp 10
VCP code 0x10 (Brightness                    ): current value =    80, max value =   100
```

```
❯ ddcutil --display 1 setvcp 10 50
Verification failed for feature 10
```

**Comment by yochananmarqos** [comment]
Oops, typo. It's HDCR, not HCDP.

**Comment by digitaltrails** [comment]
> Oops, typo. It's HDCR, not HCDP. While it's enabled, adjusting the brightness manually is disabled.

That would make sense, so that's similar to the situation I described above, in certain modes the monitor controls become unavailable.  I think that's beyond ddcutil capabilities, vdu_controls would require customisation for each monitor.

**Comment by yochananmarqos** [comment]
Right, makes sense. I'm leaving HDCR off then. Why is it adding brightness manually works, but contrast and input-source doesn't even though `setvcp` works for all three?

[Clight](https://github.com/FedeDP/Clight/) is also working now with it off.

**Comment by digitaltrails** [comment]
> Right, makes sense. I'm leaving HDCR off then. [Clight](https://github.com/FedeDP/Clight/) is also working now with it off.
> 
> Why is it adding brightness manually works, but contrast and input-source doesn't even though `getvcp` / `setvcp` works for all three?
> 
> EDIT: I also got the contrast slider to work now. Here's my current `MSI_G27C4.conf`:
> 
> ...

In theory if the set/get work, manually adding them should work.  Input source would require a multi-valued input definition for which you need to know the right values, so the conf might look something like:

```
[vdu-controls-widgets]
brightness = yes
contrast = yes
input-source = yes
power-mode = no
osd-language = no
enable-vcp-codes = 

[ddcutil-parameters]
sleep-multiplier = 0.5

[ddcutil-capabilities]
capabilities-override = Model: MSI
	MCCS version: 2.2
	Commands:
	   Command: 01 (VCP Request)
	   Command: 02 (VCP Response)
	   Command: 03 (VCP Set)
	VCP Features:
	   Feature: 10 (Brightness)
	   Feature: 12 (Contrast)
	   Feature: 60 (Input Source)
                 Values:
                     01: VGA-1
                     02: DVI-I
                     03: Display-Port1

```
I don't know what would happen if you define a source that does not exist.  My LG monitors reports that it has an input-source source that doesn't actually exist, I have tried selecting it, it did not brick my monitor, but perhaps MSI might be more picky.   According to the author of ddcutil, one person has bricked a monitor by trying manufacturer specific VCP codes.

Thanks for the point to Clight, I was not aware of it.  I originally tried writing something a bit like it as a shell script (much simpler of course), but I the second-hand web-cam my sister in law donated automatically adjusts its gain, so it was hard to work with.  Perhaps Clight might cope with it better (or I should buy a more sophisticated web-cam).  I sometime do photo processing, I wonder if dynamically altering the monitor might result in some strange results.

**Comment by digitaltrails** [comment]
I now capture failed attempts to obtain a monitor's capabilities and offer some choices:

1. Retry obtaining the capabilities.
2. Ignore the monitor (writes a config file with no capabilities to silence the problem).
3. Apply/write a config with brightness and contrast controls (may not necessarily work).

To cope better with option 3 not actually working I now also capture failures the get control values.

Here is screenshot of the message dialog:

![Screenshot_20220227_161155](https://user-images.githubusercontent.com/5510901/155866648-e4a35e4b-1ac0-43b4-b154-9d80ff482531.png)

**Comment by yochananmarqos** [comment]
That works great! Before running it, I removed `MSI_G27C4.conf` and it generated it as expected choosing Apply.

However,  now it's adding brightness and contrast controls for my laptop screen (NCP) in the UI with no configuration file. I keep my laptop lid closed.

```
INFO: checking Display 1
   I2C bus:  /dev/i2c-2
   Monitor:             MSI:MSI G27C4:
INFO: checking Display 2
   I2C bus:  /dev/i2c-3
   Monitor:             HPN:HP X24ih:1CR1261L9W
WARNING: ignoring Invalid display
   I2C bus:  /dev/i2c-4
   Monitor:             NCP::
INFO: checking Display 3
   I2C bus:  /dev/i2c-5
   Monitor:             HPN:HP X24ih:1CR1060B95
```

**Comment by digitaltrails** [comment]
> That works great! Before running it, I removed `MSI_G27C4.conf` and it generated it as expected choosing Apply.
> 
> However, now it's adding brightness and contrast controls for my laptop screen (NCP) in the UI with no configuration file. I keep my laptop lid closed.
> 

I don't have such a setup, maybe I can simulate it.   I'll look through the code to see how this might come about.

**Comment by digitaltrails** [comment]
>...
> However, now it's adding brightness and contrast controls for my laptop screen (NCP) in the UI with no configuration file. I keep my laptop lid closed.
> ...
What's in the default .config/vdu_controls/vdu_controls.conf?  One way this might happen is if enable-vcp-codes was defined as non-empty in the default file, so I like to rule that out.

**Comment by digitaltrails** [comment]
> > ...
> > However, now it's adding brightness and contrast controls for my laptop screen (NCP) in the UI with no configuration file. I keep my laptop lid closed.
> > ...
> 
> What's in the default .config/vdu_controls/vdu_controls.conf? One way this might happen is if enable-vcp-codes was defined as non-empty in the default file, so I'd like to rule that out.

I'm  puzzled by the lack of a monitor title in your screen shot.   I've check in a small change that might account for that (the code might potentially reinitialize an existing controller  in the event that a monitor cannot be interrogated for it's capabilities.  Reading the code, I'm still not quite convinced I've found the problem.

**Comment by yochananmarqos** [comment]
It never asked about my laptop display (NCP), no.

<details>
<summary>vdu_controls.conf</summary>

```
[vdu-controls-globals]
system-tray-enabled = yes
splash-screen-enabled = yes
warnings-enabled = yes
debug-enabled = yes

[vdu-controls-widgets]
brightness = yes
contrast = yes
audio-volume = no
audio-mute = no
audio-treble = no
audio-bass = no
audio-mic-volume = no
input-source = yes
power-mode = no
osd-language = no
enable-vcp-codes = 

[ddcutil-parameters]
sleep-multiplier = 0.5

[ddcutil-capabilities]
capabilities-override = 
```

</details>

Diff between the log above and with the new commit:

<details>
<summary>diff</summary>

```
--- log1	2022-02-28 09:04:16.448949392 -0700
+++ log2	2022-02-28 09:03:49.598348900 -0700
@@ -1,4 +1,3 @@
-
 INFO: checking for config file '/home/yochanan/.config/vdu_controls/vdu_controls.conf'
 INFO: using config file '/home/yochanan/.config/vdu_controls/vdu_controls.conf'
 INFO: application style is adwaita-dark
@@ -17,15 +16,31 @@
    I2C bus:  /dev/i2c-5
    Monitor:             HPN:HP X24ih:1CR1060B95
 INFO: checking for config file '/home/yochanan/.config/vdu_controls/MSI_G27C4_Display1.conf'
-INFO: checking for config file '/home/yochanan/.config/vdu_controls/MSI_G27C4.conf'
-DEBUG: subprocess run    -  ddcutil ('--display', '1', 'capabilities')
-Unable to get capabilities for monitor on Display_Handle[i2c: fd=3, busno=2 @0x55be78804590].  Maximum DDC retries exceeded.
-INFO: checking for config file '/home/yochanan/.config/vdu_controls/MSI_G27C4_Display1.conf'
-INFO: checking for config file '/home/yochanan/.config/vdu_controls/MSI_G27C4.conf'
-WARNING: creating new config file /home/yochanan/.config/vdu_controls/MSI_G27C4_Display1.conf
-WARNING: creating new config file /home/yochanan/.config/vdu_controls/MSI_G27C4.conf
+INFO: using config file '/home/yochanan/.config/vdu_controls/MSI_G27C4_Display1.conf'
+DEBUG: MSI_G27C4_Display1.conf [vdu-controls-widgets] brightness = yes
+DEBUG: MSI_G27C4_Display1.conf [vdu-controls-widgets] contrast = yes
+DEBUG: MSI_G27C4_Display1.conf [vdu-controls-widgets] audio-volume = no
+DEBUG: MSI_G27C4_Display1.conf [vdu-controls-widgets] audio-mute = no
+DEBUG: MSI_G27C4_Display1.conf [vdu-controls-widgets] audio-treble = no
+DEBUG: MSI_G27C4_Display1.conf [vdu-controls-widgets] audio-bass = no
+DEBUG: MSI_G27C4_Display1.conf [vdu-controls-widgets] audio-mic-volume = no
+DEBUG: MSI_G27C4_Display1.conf [vdu-controls-widgets] input-source = yes
+DEBUG: MSI_G27C4_Display1.conf [vdu-controls-widgets] power-mode = no
+DEBUG: MSI_G27C4_Display1.conf [vdu-controls-widgets] osd-language = no
+DEBUG: MSI_G27C4_Display1.conf [vdu-controls-widgets] enable-vcp-codes = 
+DEBUG: MSI_G27C4_Display1.conf [ddcutil-parameters] sleep-multiplier = 0.5
+DEBUG: MSI_G27C4_Display1.conf [ddcutil-capabilities] capabilities-override = capabilities-override = Model: unknown
+        MCCS version: 2.2
+        Commands:
+       Command: 01 (VCP Request)
+       Command: 02 (VCP Response)
+       Command: 03 (VCP Set)
+        VCP Features:
+           Feature: 10 (Brightness)
+           Feature: 12 (Contrast)
+           Feature: 60 (Input Source)
 DEBUG: subprocess run    -  ddcutil ('--brief', '--display', '1', 'getvcp', '10')
-DEBUG: subprocess result -  CompletedProcess(args=['ddcutil', '--sleep-multiplier', '0.5', '--brief', '--display', '1', 'getvcp', '10'], returncode=0, stdout=b'VCP 10 C 98 100\n')
+DEBUG: subprocess result -  CompletedProcess(args=['ddcutil', '--sleep-multiplier', '0.5', '--brief', '--display', '1', 'getvcp', '10'], returncode=0, stdout=b'VCP 10 C 96 100\n')
 DEBUG: subprocess run    -  ddcutil ('--brief', '--display', '1', 'getvcp', '12')
 DEBUG: subprocess result -  CompletedProcess(args=['ddcutil', '--sleep-multiplier', '0.5', '--brief', '--display', '1', 'getvcp', '12'], returncode=0, stdout=b'VCP 12 C 69 100\n')
 INFO: checking for config file '/home/yochanan/.config/vdu_controls/HP_X24ih_1CR1261L9W.conf'
@@ -168,13 +183,13 @@
       Values: 00 01 02 01 01 02 03 04 05 06 02 01 02 0A 01 0B 01 02 03 04 05 06 11 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E (interpretation unavailable)
    Feature: FF (Manufacturer specific feature)
 DEBUG: subprocess run    -  ddcutil ('--brief', '--display', '2', 'getvcp', '10')
-DEBUG: subprocess result -  CompletedProcess(args=['ddcutil', '--sleep-multiplier', '0.5', '--brief', '--display', '2', 'getvcp', '10'], returncode=0, stdout=b'VCP 10 C 85 100\n')
+DEBUG: subprocess result -  CompletedProcess(args=['ddcutil', '--sleep-multiplier', '0.5', '--brief', '--display', '2', 'getvcp', '10'], returncode=0, stdout=b'VCP 10 C 96 100\n')
 DEBUG: subprocess run    -  ddcutil ('--brief', '--display', '2', 'getvcp', '12')
 DEBUG: subprocess result -  CompletedProcess(args=['ddcutil', '--sleep-multiplier', '0.5', '--brief', '--display', '2', 'getvcp', '12'], returncode=0, stdout=b'VCP 12 C 80 100\n')
 DEBUG: subprocess run    -  ddcutil ('--brief', '--display', '2', 'getvcp', '60')
 DEBUG: subprocess result -  CompletedProcess(args=['ddcutil', '--sleep-multiplier', '0.5', '--brief', '--display', '2', 'getvcp', '60'], returncode=0, stdout=b'VCP 60 SNC x11\n')
 DEBUG: subprocess run    -  ddcutil ('--brief', '--display', '2', 'getvcp', '10')
-DEBUG: subprocess result -  CompletedProcess(args=['ddcutil', '--sleep-multiplier', '0.5', '--brief', '--display', '2', 'getvcp', '10'], returncode=0, stdout=b'VCP 10 C 85 100\n')
+DEBUG: subprocess result -  CompletedProcess(args=['ddcutil', '--sleep-multiplier', '0.5', '--brief', '--display', '2', 'getvcp', '10'], returncode=0, stdout=b'VCP 10 C 96 100\n')
 DEBUG: subprocess run    -  ddcutil ('--brief', '--display', '2', 'getvcp', '12')
 DEBUG: subprocess result -  CompletedProcess(args=['ddcutil', '--sleep-multiplier', '0.5', '--brief', '--display', '2', 'getvcp', '12'], returncode=0, stdout=b'VCP 12 C 80 100\n')
 INFO: checking for config file '/home/yochanan/.config/vdu_controls/HP_X24ih_1CR1060B95.conf'
@@ -311,7 +326,7 @@
       Values: 00 01 02 01 01 02 03 04 05 06 02 01 02 0A 01 0B 01 02 03 04 05 06 11 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E (interpretation unavailable)
    Feature: FF (Manufacturer specific feature)</details>
 DEBUG: subprocess run    -  ddcutil ('--brief', '--display', '3', 'getvcp', '10')
-DEBUG: subprocess result -  CompletedProcess(args=['ddcutil', '--sleep-multiplier', '0.5', '--brief', '--display', '3', 'getvcp', '10'], returncode=0, stdout=b'VCP 10 C 85 100\n')
+DEBUG: subprocess result -  CompletedProcess(args=['ddcutil', '--sleep-multiplier', '0.5', '--brief', '--display', '3', 'getvcp', '10'], returncode=0, stdout=b'VCP 10 C 96 100\n')
 DEBUG: subprocess run    -  ddcutil ('--brief', '--display', '3', 'getvcp', '12')
 DEBUG: subprocess result -  CompletedProcess(args=['ddcutil', '--sleep-multiplier', '0.5', '--brief', '--display', '3', 'getvcp', '12'], returncode=0, stdout=b'VCP 12 C 80 100\n')
 DEBUG: subprocess run    -  ddcutil ('--brief', '--display', '3', 'getvcp', '60')
```

</details>

**Comment by digitaltrails** [comment]
> I'm puzzled by the lack of a monitor title in your screen shot. **I've pushed a small change that might account for that** (the code might potentially reinitialize an existing controller in the event that a monitor cannot be interrogated for it's capabilities). Reading the code, I'm still not quite convinced I've found the problem. **It would be worth trying it to see if it makes a difference.**

Did the commit mentioned previously make no difference?

It does very much look like default controls for the invalid monitor are being added to the previous valid one.  I'll have to see if I can dummy up something that reproduces the situation on my desktop.

**Comment by yochananmarqos** [comment]
Other then the difference in the logs, no it didn't make any difference. There doesn't seem to be any difference whether my laptop lid is open or closed, either.

**Comment by digitaltrails** [comment]
Please could you post the content of /home/yochanan/.config/vdu_controls/HP_X24ih_1CR1261L9W.conf

I just want to see if there's anything in there that might be contributing.

**Comment by yochananmarqos** [comment]
<details>
<summary>HP_X24ih_1CR1261L9W.conf</summary>

```
[vdu-controls-widgets]
brightness = yes
contrast = yes
input-source = yes
power-mode = no
osd-language = no
enable-vcp-codes = 10,12

[ddcutil-parameters]
sleep-multiplier = 0.5

[ddcutil-capabilities]
capabilities-override = Unparsed capabilities string: (prot(monitor)type(lcd)model(HP X24ih)cmds(01 02 03 07 0C E3 F3)vcp(02 04 05 08 0B 0C 10 12 14(02 03 04 05 08 09 0B 0C 0D ) 16 18 1A 52 60(0F 11 ) 6C 6E 70 86(01 02 05) 87(01 02 03 04 05 06 07) AA(01 02) AC AE B2 B6 C0 C6 C8 C9 CA(01 02) CC(01 02 03 04 05 06 08 0A 0D 14) D6(01 02 03 04 05) DA(00 02 ) DC (00 (00 10 13 14 15 17 1A 1D 1E ) 01 02 03) E0(02 (00 01 02) ) E1(02 (00 01) 03 (00 01 02 03 04 05 06 07) 04 (00 01) 0F (00 01) 10 (00 01) 27 (02 03 04 05 07 ) ) DF E6(00 01) E7(00 01) E8(00 ( 01 02 03 ) 01 02 03 04 05 06 80 81 82 83 84 85 86 ) E9(00 01) EA(00 01) EB(00 (00 01 02 03 04 ) ) DE(00 (00 01 06 07 ) ) ED(00 01) EE(01 02 03) EE(01 02 03) F4(00 (00 01 02 03) 01 (00 01 02 03 04 05 06 07) 02 (00 01 02 03) 0A (00 01 05) 0B (00 01 02 03 04 05 06 07) 11 (00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F) )  FF)mswhql(1)asset_eep(40)mccs_ver(2.2))
	Errors parsing capabilities string:
	   Feature ( (Invalid code)
	   Invalid VCP value in list for feature xe0: 02 (00 01 02) 
	   Invalid VCP value in list for feature xe1: 02 (00 01) 03 (00 01 02 03 04 05 06 07) 04 (00 01) 0F (00 01) 10 (00 01) 27 (02 03 04 05 07 ) 
	   Invalid VCP value in list for feature xe8: 00 ( 01 02 03 ) 01 02 03 04 05 06 80 81 82 83 84 85 86 
	   Invalid VCP value in list for feature xeb: 00 (00 01 02 03 04 ) 
	   Invalid VCP value in list for feature xde: 00 (00 01 06 07 ) 
	   Invalid VCP value in list for feature xf4: 00 (00 01 02 03) 01 (00 01 02 03 04 05 06 07) 02 (00 01 02 03) 0A (00 01 05) 0B (00 01 02 03 04 05 06 07) 11 (00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F) 
	Model: HP X24ih
	MCCS version: 2.2
	Commands:
	   Op Code: 01 (VCP Request)
	   Op Code: 02 (VCP Response)
	   Op Code: 03 (VCP Set)
	   Op Code: 07 (Timing Request)
	   Op Code: 0C (Save Settings)
	   Op Code: E3 (Capabilities Reply)
	   Op Code: F3 (Capabilities Request)
	VCP Features:
	   Feature: 02 (New control value)
	   Feature: 04 (Restore factory defaults)
	   Feature: 05 (Restore factory brightness/contrast defaults)
	   Feature: 08 (Restore color defaults)
	   Feature: 0B (Color temperature increment)
	   Feature: 0C (Color temperature request)
	   Feature: 10 (Brightness)
	   Feature: 12 (Contrast)
	   Feature: 14 (Select color preset)
	      Values:
	         02: Display Native
	         03: 4000 K
	         04: 5000 K
	         05: 6500 K
	         08: 9300 K
	         09: 10000 K
	         0b: User 1
	         0c: User 2
	         0d: User 3
	   Feature: 16 (Video gain: Red)
	   Feature: 18 (Video gain: Green)
	   Feature: 1A (Video gain: Blue)
	   Feature: 52 (Active control)
	   Feature: 60 (Input Source)
	      Values:
	         0f: DisplayPort-1
	         11: HDMI-1
	   Feature: 6C (Video black level: Red)
	   Feature: 6E (Video black level: Green)
	   Feature: 70 (Video black level: Blue)
	   Feature: 86 (Display Scaling)
	      Values:
	         01: No scaling
	         02: Max image, no aspect ration distortion
	         05: Max vertical image with aspect ratio distortion
	   Feature: 87 (Sharpness)
	      Values: 01 02 03 04 05 06 07 (interpretation unavailable)
	   Feature: AA (Screen Orientation)
	      Values:
	         01: 0 degrees
	         02: 90 degrees
	   Feature: AC (Horizontal frequency)
	   Feature: AE (Vertical frequency)
	   Feature: B2 (Flat panel sub-pixel layout)
	   Feature: B6 (Display technology type)
	   Feature: C0 (Display usage time)
	   Feature: C6 (Application enable key)
	   Feature: C8 (Display controller type)
	   Feature: C9 (Display firmware level)
	   Feature: CA (OSD/Button Control)
	      Values:
	         01: OSD disabled, button events enabled
	         02: OSD enabled, button events enabled
	   Feature: CC (OSD Language)
	      Values:
	         01: Chinese (traditional, Hantai)
	         02: English
	         03: French
	         04: German
	         05: Italian
	         06: Japanese
	         08: Portuguese (Portugal)
	         0a: Spanish
	         0d: Chinese (simplified / Kantai)
	         14: Dutch
	   Feature: D6 (Power mode)
	      Values:
	         01: DPM: On,  DPMS: Off
	         02: DPM: Off, DPMS: Standby
	         03: DPM: Off, DPMS: Suspend
	         04: DPM: Off, DPMS: Off
	         05: Write only value to turn off display
	   Feature: DA (Scan mode)
	      Values:
	         00: Normal operation
	         02: Overscan
	   Feature: DC (Display Mode)
	   Feature: E0 (Manufacturer specific feature)
	      Values: 02 01 (interpretation unavailable)
	   Feature: E1 (Manufacturer specific feature)
	      Values: 02 03 01 02 03 04 05 06 04 0F 10 27 03 04 05 07 (interpretation unavailable)
	   Feature: DF (VCP Version)
	   Feature: E6 (Manufacturer specific feature)
	      Values: 00 01 (interpretation unavailable)
	   Feature: E7 (Manufacturer specific feature)
	      Values: 00 01 (interpretation unavailable)
	   Feature: E8 (Manufacturer specific feature)
	      Values: 00 01 02 03 01 02 03 04 05 06 80 81 82 83 84 85 86 (interpretation unavailable)
	   Feature: E9 (Manufacturer specific feature)
	      Values: 00 01 (interpretation unavailable)
	   Feature: EA (Manufacturer specific feature)
	      Values: 00 01 (interpretation unavailable)
	   Feature: EB (Manufacturer specific feature)
	      Values: 00 01 02 03 04 (interpretation unavailable)
	   Feature: DE (Scratch Pad)
	      Values: 00 01 06 07 (interpretation unavailable)
	   Feature: ED (Manufacturer specific feature)
	      Values: 00 01 (interpretation unavailable)
	   Feature: EE (Manufacturer specific feature)
	      Values: 01 02 03 (interpretation unavailable)
	   Feature: EE (Manufacturer specific feature)
	      Values: 01 02 03 (interpretation unavailable)
	   Feature: F4 (Manufacturer specific feature)
	      Values: 00 01 02 01 01 02 03 04 05 06 02 01 02 0A 01 0B 01 02 03 04 05 06 11 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E (interpretation unavailable)
	   Feature: FF (Manufacturer specific feature)

```

</details>

**Comment by digitaltrails** [comment]
Looking at /home/yochanan/.config/vdu_controls/HP_X24ih_1CR1261L9W.conf

I think having both 
```
brightness = yes
contrast = yes
```
and

```
enable-vcp-codes = 10,12
``` 

might be the actual cause of the doubling of controls for "display" 2.

Please could you try removing either one of the two and see if it makes a difference.

**Comment by yochananmarqos** [comment]
Yep, that was it. Working as intended! :laughing:

**Comment by digitaltrails** [comment]
> Yep, that was it. Working as intended! laughing

Thanks.  I will add some code to ensure that if a control is enabled by either method it will only be included once.

**Comment by digitaltrails** [comment]
> > Yep, that was it. Working as intended! laughing
> 
> Thanks. I will add some code to ensure that if a control is enabled by either method it will only be included once.

I've added code to cover this and pushed it.  Maybe the GUI should also warn about this, but that's a much bigger effort, so I think I will leave that alone for now.
