### ISSUE TITLE
Issues with debug or syslog enabled

### ISSUE THREAD

**Issue by yochananmarqos** [digitaltrails/vdu_controls#22]
With no config files, v1.6.9 starts up fine. However, after enabling debug and/or syslog, it complains `sleep-multiplier` might be set too low. It's set to the default 0.5.

If `debug-enabled` is `yes`:
```
INFO checking for config file '/home/yochanan/.config/vdu_controls/vdu_controls.conf'
INFO using config file '/home/yochanan/.config/vdu_controls/vdu_controls.conf'
INFO application style is adwaita-dark
INFO using system tray.
ERROR 
Traceback (most recent call last):
  File "/usr/bin/vdu_controls", line 2870, in <module>
    main()
  File "/usr/bin/vdu_controls", line 2708, in main
    main_window = MainWindow(main_config, app, session_startup=is_logging_in())
  File "/usr/bin/vdu_controls", line 2541, in __init__
    self.main_control_panel = VduControlsMainPanel(main_config, detect_vdu_hook, app_context_menu, session_startup)
  File "/usr/bin/vdu_controls", line 1832, in __init__
    self.detected_vdus = self.ddcutil.detect_monitors()
  File "/usr/bin/vdu_controls", line 629, in detect_monitors
    result = self.__run__('detect', '--terse')
  File "/usr/bin/vdu_controls", line 617, in __run__
    log_debug("subprocess run    - ", DDCUTIL, args)
TypeError: log_debug() takes 1 positional argument but 3 were given
```

if `debug-enabled` and `syslog-enabled` are both `yes`:

```
INFO checking for config file '/home/yochanan/.config/vdu_controls/vdu_controls.conf'
INFO using config file '/home/yochanan/.config/vdu_controls/vdu_controls.conf'
INFO application style is adwaita-dark
INFO using system tray.
ERROR 
Traceback (most recent call last):
  File "/usr/bin/vdu_controls", line 2870, in <module>
    main()
  File "/usr/bin/vdu_controls", line 2708, in main
    main_window = MainWindow(main_config, app, session_startup=is_logging_in())
  File "/usr/bin/vdu_controls", line 2541, in __init__
    self.main_control_panel = VduControlsMainPanel(main_config, detect_vdu_hook, app_context_menu, session_startup)
  File "/usr/bin/vdu_controls", line 1832, in __init__
    self.detected_vdus = self.ddcutil.detect_monitors()
  File "/usr/bin/vdu_controls", line 629, in detect_monitors
    result = self.__run__('detect', '--terse')
  File "/usr/bin/vdu_controls", line 617, in __run__
    log_debug("subprocess run    - ", DDCUTIL, args)
TypeError: log_debug() takes 1 positional argument but 3 were given

Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/bin/vdu_controls", line 2267, in exception_handler
    log_error("\n" + ''.join(traceback.format_exception(e_type, e_value, e_traceback)))
  File "/usr/bin/vdu_controls", line 567, in log_error
    syslog.syslog(syslog.LOG_ERROR, str) if log_to_syslog else None
AttributeError: module 'syslog' has no attribute 'LOG_ERROR'. Did you mean: 'LOG_PERROR'?

Original exception was:
Traceback (most recent call last):
  File "/usr/bin/vdu_controls", line 2870, in <module>
    main()
  File "/usr/bin/vdu_controls", line 2708, in main
    main_window = MainWindow(main_config, app, session_startup=is_logging_in())
  File "/usr/bin/vdu_controls", line 2541, in __init__
    self.main_control_panel = VduControlsMainPanel(main_config, detect_vdu_hook, app_context_menu, session_startup)
  File "/usr/bin/vdu_controls", line 1832, in __init__
    self.detected_vdus = self.ddcutil.detect_monitors()
  File "/usr/bin/vdu_controls", line 629, in detect_monitors
    result = self.__run__('detect', '--terse')
  File "/usr/bin/vdu_controls", line 617, in __run__
    log_debug("subprocess run    - ", DDCUTIL, args)
TypeError: log_debug() takes 1 positional argument but 3 were given
```

**Comment by digitaltrails** [comment]
OK, the logging code was a bit rough (coding while tired).  Making a new release now.

**Comment by yochananmarqos** [comment]
1.6.10 did the trick. :+1:
