### ISSUE TITLE
Error: TypeError: callable must be a method of a QtCore.QObject

### ISSUE THREAD

**Issue by Milor123** [digitaltrails/vdu_controls#78]
Hi guys!! I've updated my vdu and now cant open the program.

![image](https://github.com/digitaltrails/vdu_controls/assets/14153649/75b09d67-bab4-4b1a-8cf9-daeae87a2b3f)

Error: TypeError: callable must be a method of a QtCore.QObject instance decorated by QtCore.pyqtSlot

![image](https://github.com/digitaltrails/vdu_controls/assets/14153649/acdbbbaa-b958-4cc3-b07f-35a11b63fc3b)

Details:
```
Details: Traceback (most recent call last):
  File "/home/noe/bin/vdu_controls", line 8441, in <module>
    main()
  File "/home/noe/bin/vdu_controls", line 8363, in main
    VduAppWindow(main_config, app, main_controller)  # may need to assign this to a variable to prevent garbage collection?
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noe/bin/vdu_controls", line 7830, in __init__
    self.main_controller.configure_application(self)
  File "/home/noe/bin/vdu_controls", line 7234, in configure_application
    self.create_ddcutil()
  File "/home/noe/bin/vdu_controls", line 7275, in create_ddcutil
    self.ddcutil = Ddcutil(common_args=self.main_config.get_ddcutil_extra_args(),
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noe/bin/vdu_controls", line 1252, in __init__
    self.ddcutil_impl = DdcutilDBusImpl(self.common_args, callback=connected_vdus_changed_callback)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noe/bin/vdu_controls", line 1645, in __init__
    self.ddcutil_proxy, self.ddcutil_props_proxy = self._connect_to_service()
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noe/bin/vdu_controls", line 1693, in _connect_to_service
    session_bus.connect(dbus_service_name, dbus_object_path, self.dbus_interface_name,
TypeError: callable must be a method of a QtCore.QObject instance decorated by QtCore.pyqtSlot

```

when I try run directly using the terminal show this

```
python vdu_controls.py          
19:26:50 INFO: VDU Controls 2.0.2 vdu_controls.py  
19:26:50 INFO: python-locale: ('es_ES', 'UTF-8') Qt-locale: es_ES
19:26:50 INFO: app-style: breeze (detected a dark theme)
19:26:50 INFO: Looking for config file '/home/noe/.config/vdu_controls/vdu_controls.conf'
19:26:50 INFO: Using config file '/home/noe/.config/vdu_controls/vdu_controls.conf'
19:26:50 INFO: Logging to stdout
19:26:50 INFO: Reading autolux file '/home/noe/.config/vdu_controls/AutoLux.conf'
19:26:50 INFO: native_font_height_pixels=18
19:26:50 INFO: Using system tray.
19:26:50 INFO: Configuring application (reconfiguring=False)...
19:26:50 ERROR: Sanity check try 1: com.ddcutil.DdcutilInterface failed: The name is not activatable
19:26:52 ERROR: 

Here is the error mentioned above ....
```

what should i do? 
Thank u very much !

**Comment by digitaltrails** [comment]
I had an error like that this morning (local time), I thought I had fixed it, at least it's working for me. Have you pulled the latest in the last couple of hours?

**Comment by digitaltrails** [comment]
Still looking. In the meantime you could edit `$HOME/.config/vdu_controls/vdu_controls.conf` and find the line `dbus-client-enabled = yes` and set it to `dbus-client-enabled = no`.  That will bypass the problem code.

**Comment by digitaltrails** [comment]
I've made a temporary patch which catches the problem and works around it.  

When I have time I will investigate it further.  Thanks for bringing this to my attention, because I personally use ddcutil-service I had not noticed I broke using the ddcutil command.
